trigger: none
pr: none
name: NightlyRun-UI-$(Date:yyyy-MM-dd)$(Rev:.r)

extends:
    template: .azure/playwright-job.yml
    parameters:
        project: ui
        testRunTitle: 'End-To-End Automated UI Tests'
        installBrowsers: true
